version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    command: >
      sh -c "echo 'CREATE EXTENSION IF NOT EXISTS \"enum\";' | docker-entrypoint.sh postgres && tail -f /dev/null"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
